### ISSUE TITLE
not compatible with non-pro queues

### ISSUE THREAD

**Issue by jaroslaw-weber** [taskforcesh/bullmq-pro-support#37]
i have many queues and did not want to convert all of them to bullmq pro yet & leave an option to roll back in case of any issue.
but it seems i get some conflicts if i use both bullmq pro & bullmq.

im getting this error:

```
eplyError: ERR Error running script (call to f_889b7c3cc3518604404f435d4686fbc6b059af58): @user_script:135: user_script:135: attempt to perform arithmetic on local 'timestamp' (a nil value)
    at parseError (/Users/x/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/x/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      '889b7c3cc3518604404f435d4686fbc6b059af58',
      '9',
      'server:bullmq:connector-queue-appsFlyer:wait',
      'server:bullmq:connector-queue-appsFlyer:active',
      'server:bullmq:connector-queue-appsFlyer:priority',
      'server:bullmq:connector-queue-appsFlyer:events',
      'server:bullmq:connector-queue-appsFlyer:stalled',
      'server:bullmq:connector-queue-appsFlyer:limiter',
      'server:bullmq:connector-queue-appsFlyer:delayed',
      'server:bullmq:connector-queue-appsFlyer:delay',
      'server:bullmq:connector-queue-appsFlyer:',
      '1673923322048',
      '',
      <Buffer de 00 03 a5 74 6f 6b 65 6e d9 24 35 38 37 33 30 61 63 38 2d 33 38 35 62 2d 34 31 66 62 2d 38 61 35 38 2d 61 30 62 61 64 36 34 65 62 30 61 62 ac 6c 6f ... 66 more bytes>,
      '5',
      '4000',
      'true'
    ]
  }
}
```

**Comment by for2gles** [comment]
I fixed this issue by making two redis connection and set BullMQ and BullMQPro connection each not using same connection

**Comment by roggervalf** [comment]
Having @for2gles solution, we can close this issue
