### ISSUE TITLE
`loadIncludes` breaks with 1.57.0

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq-pro-support#4]
When upgrading from bullmq "1.54.6" to "1.57.0" with pro version 

```
 cloud:QueueWorker <5> Unable to start queue TypeError: (intermediate value).loadIncludes is not a function +1ms
    at RedisConnectionPro.loadCommands (/opt/qumulex/app/node_modules/@taskforcesh/bullmq-pro/src/classes/redis-connection-pro.ts:7:34)
    at RedisConnectionPro.init (/opt/qumulex/app/node_modules/bullmq/src/classes/redis-connection.ts:134:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 ```

**Comment by roggervalf** [comment]
@lukepolo could you please try the last version 1.1.6 when you get a chance
