### ISSUE TITLE
removeRepeatable is not a function (BullMQ Pro 1.1.5 + BullMQ 1.54.6)

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq-pro-support#5]
Missing Remove Repeatable Job 

```
node:790) UnhandledPromiseRejectionWarning: TypeError: client.removeRepeatable is not a function
    at Repeat.removeRepeatableByKey (/opt/qumulex/app/node_modules/@taskforcesh/bullmq-pro/node_modules/bullmq/src/classes/repeat.ts:151:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by manast** [comment]
Thanks for reporting, we are looking into this.
